image: continuumio/miniconda3:latest

before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -n base conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - cd .test/
  - bash generate_data.sh ${PYTHON_VERSION}
  - cd ../

tests:
  stage: test
  script:
    - source activate bollito_snakemake
    - snakemake --use-conda --directory .test
