image: continuumio/miniconda3:latest

before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda create -q -n snakemake snakemake python=${PYTHON_VERSION}
  - git clone http://gitlab.com/bu_cnio/sc-test-data .test/data
  - source activate snakemake
  - cd .test/data
  - snakemake --use-conda
  - cd ../../
  - conda create -q -n prep star=2.7.1a
  - source activate prep
  - mkdir .test/data/ref/genome.chr19.fa_idx
  - STAR --runMode genomeGenerate --genomeDir .test/data/ref/genome.chr19.fa_idx --genomeFastaFiles .test/data/ref/genome.chr19.fa --genomeSAindexNbases 11

tests:
  stage: test
  script:
    - source activate snakemake
    - snakemake --use-conda --directory .test
