# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

outdir: 'projects/test/out'
logdir: 'projects/test/log'

ref:
    # gtf file with transcripts
    annotation: "res/genome/gencode.vM20.annotation.gtf"
    # fasta file of the genome
    sequence: "res/genome/GRCm38.primary_assembly.genome.fa"

# barcodes whitelist
whitelist: "res/whitelists/3M-february-2018.txt"

rules:
    default:
        res:
            threads: 1
            mem: 2000
    cutadapt:
        params: "-G GCAGTGGTATCAACGCAGAGTACATGGG -m 16"
    fastq_screen_indexes:
        threads: 8
        outdir: "res"
    fastq_screen:
        threads: 8
        disabled: false
    star_index:
        res:
            threads: 6
            mem: 64000
    star:
        params: "--soloType Droplet --soloFeatures Gene --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --alignEndsType EndToEnd --outReadsUnmapped Fastx --soloUMIlen 12 --outSAMtype BAM SortedByCoordinate"
        res:
            threads: 6
            mem: 64000
    fastqc:
        res:
            threads: 4
    rseqc_junction_saturation:
        res:
            mem: 8000
    rseqc_readdup:
        res:
            mem: 24000
